baseURL = "https://blockndevcom"
languageCode = "ru"
title = "Блокчейн & Разработка"
description = "Блог о разработке и блокчейн-технологиях. Код, сети, паранойя."

theme = "contrast-hugo"

[params]
    description = "Блог о разработке и блокчейн-технологиях. Код, сети, паранойя."
    longDescription = "Блог о блокчейн-технологиях и разработке. Код, сети, криптография, паранойя — вот это вот всё. Копаем глубоко, находим самое сутевое."